# pd-else/Source/Extra/Aliases:
# [lb] and [s2f~] are always automatically included because they are used in a lot of abstractions.
# all the other aliases are excluded.

set(PICKED_ELSE_EXTERNALS
    # Commented-out externals are not included in the build.

    # circuit~ — depends on LGPL libs, heavy; not referenced in any abstractions
    # plaits~ — maybe later. referenced in plaits.m~ Merda module
    # sfont~ — GPL, heavy; referenced in sfont.m~ Merda module
    # sfz~ — BSD 2, but heavy; not referenced in any abstractions
    # lua — GPL; not referenced in any abstractions

    above~
    add~
    adsr~
    allpass.2nd~
    allpass.rev~
    asr~
    autofade.mc~
    autofade~
    autofade2.mc~
    autofade2~
    balance~
    bandpass~
    bandstop~
    # beat~ — GPL; not referenced in any abstractions
    biquads~
    bitnormal~
    bl.imp~
    bl.imp2~
    bl.saw~
    bl.saw2~
    bl.square~
    bl.tri~
    bl.vsaw~
    blocksize~
    brown~
    car2pol~
    ceil~
    cents2ratio~
    chance~
    changed~
    changed2~
    comb.filt~
    comb.rev~
    # conv~ — GPL; not referenced in any abstractions
    cosine~
    crackle~
    crossover~
    cusp~
    db2lin~
    dbgain~
    decay~
    del.in~
    del.out~
    delace~
    detect~
    downsample~
    drive~
    dust~
    dust2~
    envgen~
    eq~
    fader~
    fbdelay~
    fbsine~
    fbsine2~
    fdn.rev~
    ffdelay~
    filterdelay~
    floor~
    fm~
    fold~
    follow~
    freq.shift~
    function~
    gate2imp~
    gatedelay~
    gaussian~
    gbman~
    gendyn~
    get~
    # giga.rev~ — GPL; not referenced in any abstractions
    glide~
    glide2~
    gray~
    group~
    henon~
    highpass~
    highshelf~
    ikeda~
    impseq~
    impulse~
    impulse2~
    lace~
    lag~
    lag2~
    lastvalue~
    latoocarfian~
    lfnoise~
    lin2db~
    lincong~
    logistic~
    lop2~
    lorenz~
    lowpass~
    lowshelf~
    match~
    median~
    merge~
    mix~
    mov.avg~
    mov.rms~
    mtx.mc~
    mtx~
    nchs~
    numbox~
    nyquist~
    op~
    pan.mc~
    pan.stereo~
    pan~
    pan2~
    pan4~
    parabolic~
    # pdlink~ — heavy; not referenced in any abstractions
    peak~
    phaseseq~
    pick~
    pimp~
    pimpmul~
    pink~
    # play.file~ — heavy, depends on ffmpeg. vanilla [readsf~] should be enough. referenced in (unreleased?) strip Merda module
    pluck~
    pm~
    pm2~
    pm4~
    pm6~
    pol2car~
    power~
    pulse~
    pulsecount~
    pulsediv~
    quad~
    quantizer~
    ramp~
    rampnoise~
    rand.f~
    rand.i~
    randpulse~
    randpulse2~
    range~
    ratio2cents~
    repeat~
    rescale~
    resonant~
    resonator~
    resonator2~
    rint~
    rms~
    rotate.mc~
    rotate~
    saw~
    saw2~
    schmitt~
    scope~
    select~
    sequencer~
    sh~
    shaper~
    sig2float~
    sin~
    sine~
    slew~
    slew2~
    slice~
    smooth~
    smooth2~
    spread.mc~
    spread~
    square~
    sr~
    standard~
    status~
    stepnoise~
    sum~
    susloop~
    svfilter~
    tabplayer~
    tabreader~
    tabwriter~
    tanh~
    tempo~
    timed.gate~
    toggleff~
    tri~
    trig.delay~
    trighold~
    trunc~
    unmerge~
    velvet~
    vsaw~
    vu~
    wavetable~
    white~
    width~
    wrap2~
    wt2d~
    xfade.mc~
    xfade~
    xgate.mc~
    xgate~
    xgate2.mc~
    xgate2~
    xmod~
    xmod2~
    xselect.mc~
    xselect~
    xselect2.mc~
    xselect2~
    zerocross~

    args
    bend.in
    bend.out
    bicoeff
    bicoeff2
    break
    buffer
    button
    canvas.active
    canvas.bounds
    canvas.edit
    canvas.gop
    canvas.mouse
    canvas.name
    canvas.pos
    canvas.setname
    canvas.vis
    canvas.zoom
    ceil
    cents2ratio
    chance
    changed
    click
    closebang
    colors
    ctl.in
    ctl.out
    datetime
    default
    delace
    dollsym
    # else — does not do much in libpd; calls lua_setup. TODO: maybe stub lua_setup() just like sys_putmidibyte?
    factor
    float2bits
    floor
    fold
    fontsize
    format
    function
    gcd
    hot
    hz2rad
    initmess
    keyboard
    keycode
    knob
    lace
    limit
    loadbanger
    loop
    merge
    message
    messbox
    metronome
    midi
    mouse
    mpe.in
    note
    note.in
    note.out
    noteinfo
    openfile
    order
    osc.format
    osc.parse
    osc.route
    pack2
    pad
    panic
    # pdlink — heavy; not referenced in any abstractions
    pgm.in
    pgm.out
    pic
    pipe2
    popmenu
    properties
    ptouch.in
    ptouch.out
    quantizer
    rad2hz
    rand.f
    rand.hist
    rand.i
    rand.u
    ratio2cents
    rec
    receiver
    rescale
    retrieve
    rint
    route2
    routeall
    router
    routetype
    selector
    sender
    separate
    # sfinfo — heavy, depends on ffmpeg
    # sfload — heavy, depends on ffmpeg. vanilla [soundfiler] should be enough
    #   ^ those two objects are used in the following abstractions:
    #     - gran.player~
    #     - player~
    #     - pvoc.player~
    #     - sample~
    #     - brane.m~
    #   none of the abstractions have any dependants.
    slice
    sort
    spread
    suspedal
    symbol2any
    tabreader
    touch.in
    touch.out
    trunc
    unique
    unmerge
    var
    voices
    wrap2
)
